# Desafio 9: El Salto del Error
for numero in range(0, 5):
    if numero == 2:
        continue
    print(numero)
# salida: 0 1 3 4
